version: '3'

services:

  app:
    build: ./docker/app/
    ports:
      - 80:80
    volumes:
      - .:/var/www/app
      - ./docker/app/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/app/default-nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - database

  database:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    volumes:
      - ${DB_BACKUP_PATH}/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT_EXPOSE}:3306

  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/netdata/netdata.conf:/etc/netdata/netdata.conf
